
services:

  db:
    image: petshop_db
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: petshopdb
      MYSQL_ROOT_PASSWORD: root
    restart: always

  api:
    image: petshop_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PetDatabase=Server=db;Database=petshopdb;User=root;Password=root;Port=3306"
    depends_on:
      - db
  
  app:
    image: petshop_app
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "8080:80"